<?php

/**
 * Implementation of hook_form_alter().
 *
 * Add a simple form element to specify the rewrite rules.
 */
function rewrite_rules_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'site_node_form') {
    $node = $form['#node'];

    _hosting_site_field($form, $node, 'redirect_rules', array(
        '#type' => 'textarea',
        '#title' => t('Redirect Rules'),
        '#required' => FALSE,
        //'#description' => t('The database server the site will use to host its content.'),
        '#default_value' => isset($node->redirect_rules) ? $node->redirect_rules : '',
    ), $filter_display ='filter_xss', $editable = TRUE );
  }
}

/**
 * Implementation of hook_nodeapi().
 *
 * Just store and load the rewrite_rules field in/from the variable table.
 */
function rewrite_rules_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'update':
      if (isset($node->redirect_rules)) {
        variable_set('rewrite_rules_' . $node->nid . '_path', $node->redirect_rules);
      }
      break;
    case 'insert':
      if (isset($node->redirect_rules)) {
        variable_set('rewrite_rules_' . $node->nid . '_path', $node->redirect_rules);
      }
      break;
    case 'load':
      $additions = array();

      $path = variable_get('rewrite_rules_' . $node->nid . '_path', NULL);
      if (!is_null($path)) {
        $additions['redirect_rules'] = $path;
      }

      return $additions;
  }
}
